#define LOG_TRACE SPDLOG_TRACE
#define LOG_DEBUG SPDLOG_DEBUG
#define LOG_INFO SPDLOG_INFO
#define LOG_WARN SPDLOG_WARN
#define LOG_ERROR SPDLOG_LEVEL_ERROR
#define LOG_FATAL SPDLOG_CRITICAL
#define LOG_OFF SPDLOG_LEVEL_OFF
